name:                tbqueue-livelock
version:             0.1.0.0
github:              "githubuser/tbqueue-livelock"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tbqueue-livelock#readme>

dependencies:
- base >= 4.7 && < 5
- async
- primitive
- random
- stm
- timeit
- vector

library:
  source-dirs: src
  ghc-options:
  - -O2

benchmarks:
  benchmark:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N40
    dependencies:
    - tbqueue-livelock
    - gauge
